### PR TITLE
Qr code creator Exploration 1

### PR DESCRIPTION
**Pull request by hwalker1**

### CODE REVIEW

**Comment by fgmart-zz** [comment]
Henry -- looks fine. Uploaded source file should have a `.rkt` suffix. Please fix.

**Comment by fgmart-zz** [comment]
Henry I am closing this with a grade of 1/2. If you make the improvements I requested, I will regrade. Deadline is Wednesday this week.

**Comment by hwalker1** [comment]
Sorry for not checking my email earlier, I re-uploaded the source file with
the proper suffix and thank you very much for the reconsideration.

**Comment by hwalker1** [comment]
Is everything all set? Also I apologize again for missing your messages.

**Comment by fgmart-zz** [comment]
all set.

**Pull request closed without merging**
