### PR TITLE
FP1-Exploration1-Derek_Ross

### PR DESCRIPTION
**Pull request by DerekR0123**
OPL - Spring 17  , Part one of Final Project Sequence - Exploration 1.

 Web Applications In Racket - #lang web-server/insta

### CODE REVIEW

**Comment by fgmart-zz** [comment]
Derek,

Please format the inline code using the triple-backslash markdown so that it appears in a monospaced font.

Also, the exploration code file should have a .rkt suffix.

Please resolve these two issues and I will approve. good work.

**Comment by DerekR0123** [comment]
Okay you are going to think I'm an idiot but I have no idea what you mean
by the triple space format backslash stuff

Sorry professor

**Comment by fgmart-zz** [comment]
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by fgmart-zz** [comment]
Looks good Derek 👍

**Pull request closed without merging**
