### PR TITLE
Kimste2 patch 1

### PR DESCRIPTION
**Pull request by kimste2**
FP1 submission 
Steve

### CODE REVIEW

**Comment by fgmart-zz** [comment]
Kimste2 -- you didn't do the work yet. You're not supposed to issue the pull request until it's ready for me to look at.

Please continue work on this. Next time, please do **not** pull request until it's done.

Put your real name in the FP1 repository; I don't  know who this is.

**Comment by fgmart-zz** [comment]
I figured out that this is Steve Kim. Hi, Steve.

You've forked the repo successfully, but you still need to do the assignment, and then edit the `README.md` file to provide your report.

**Comment by fgmart-zz** [comment]
Steve

I found your work, it's in a separate branch:

https://github.com/kimste2/FP1/tree/kimste2-patch-1

You need to figure out how to merge this into master.

Also, you need to:

* get the image displayed in the narrative.

* display code as monospaced font, either by enclosing it with single-backquotes `this is code` or as a block with triple backquotes

```
this is a block of code
```

Please fix and email me when it's done.

**Comment by fgmart-zz** [comment]
Steve your work is merged into master.

But, you have to get the image to show up in the README.md. 

See the original FP1 for an example.

**Comment by kimste2** [comment]
Hi Fred


I  just updated the README.md file with the pictures a bit after you sent this.


Steve

________________________________

**Comment by fgmart-zz** [comment]
Yay, mission accomplished!

**Pull request closed without merging**
