### PR TITLE
Van Ha FP1

### PR DESCRIPTION
**Pull request by VanHaUML**

### CODE REVIEW

**Comment by fgmart-zz** [comment]
Van, I see that you played with `plot`, but this is incomplete work. Please finish it and add a comment when you are done.

**Comment by fgmart-zz** [comment]
I am recording a provisional grade. Please update the repo by Wed and I will regrade. Add comment when done.

**Comment by VanHaUML** [comment]
Added a histogram of the count of each word read from a file and a plot of a lissajous curve.

**Comment by fgmart-zz** [comment]
Nice! Re-grade completed.

**Pull request closed without merging**
